[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
whitelist_sale = "5j4KSp5cfLnt2puNbQJtepfe3Cjpcyi6Gd8cC5rs9ThL"

[registry]
url = "https://api.devnet.solana.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = 'C:\Users\ABKen\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
